// Generated by gencpp from file movo_msgs/KinovaActuatorFdbk.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_KINOVAACTUATORFDBK_H
#define MOVO_MSGS_MESSAGE_KINOVAACTUATORFDBK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movo_msgs
{
template <class ContainerAllocator>
struct KinovaActuatorFdbk_
{
  typedef KinovaActuatorFdbk_<ContainerAllocator> Type;

  KinovaActuatorFdbk_()
    : header()
    , current()
    , temperature()  {
    }
  KinovaActuatorFdbk_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current(_alloc)
    , temperature(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _current_type;
  _current_type current;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _temperature_type;
  _temperature_type temperature;




  typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const> ConstPtr;

}; // struct KinovaActuatorFdbk_

typedef ::movo_msgs::KinovaActuatorFdbk_<std::allocator<void> > KinovaActuatorFdbk;

typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk > KinovaActuatorFdbkPtr;
typedef boost::shared_ptr< ::movo_msgs::KinovaActuatorFdbk const> KinovaActuatorFdbkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace movo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'movo_msgs': ['/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4c6d57595be8397a51a210a33d3ba9e";
  }

  static const char* value(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4c6d57595be8397ULL;
  static const uint64_t static_value2 = 0xa51a210a33d3ba9eULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/KinovaActuatorFdbk";
  }

  static const char* value(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[] current\n\
float32[] temperature\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinovaActuatorFdbk_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::KinovaActuatorFdbk_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current[i]);
    }
    s << indent << "temperature[]" << std::endl;
    for (size_t i = 0; i < v.temperature.size(); ++i)
    {
      s << indent << "  temperature[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.temperature[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_KINOVAACTUATORFDBK_H
