// Generated by gencpp from file movo_msgs/PVA.msg
// DO NOT EDIT!


#ifndef MOVO_MSGS_MESSAGE_PVA_H
#define MOVO_MSGS_MESSAGE_PVA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movo_msgs
{
template <class ContainerAllocator>
struct PVA_
{
  typedef PVA_<ContainerAllocator> Type;

  PVA_()
    : pos_rad(0.0)
    , vel_rps(0.0)
    , acc_rps2(0.0)  {
    }
  PVA_(const ContainerAllocator& _alloc)
    : pos_rad(0.0)
    , vel_rps(0.0)
    , acc_rps2(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_rad_type;
  _pos_rad_type pos_rad;

   typedef float _vel_rps_type;
  _vel_rps_type vel_rps;

   typedef float _acc_rps2_type;
  _acc_rps2_type acc_rps2;




  typedef boost::shared_ptr< ::movo_msgs::PVA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movo_msgs::PVA_<ContainerAllocator> const> ConstPtr;

}; // struct PVA_

typedef ::movo_msgs::PVA_<std::allocator<void> > PVA;

typedef boost::shared_ptr< ::movo_msgs::PVA > PVAPtr;
typedef boost::shared_ptr< ::movo_msgs::PVA const> PVAConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movo_msgs::PVA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movo_msgs::PVA_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace movo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'movo_msgs': ['/home/andrewandjasmine/movo_ws/src/movo_common/movo_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::PVA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movo_msgs::PVA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::PVA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movo_msgs::PVA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::PVA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movo_msgs::PVA_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movo_msgs::PVA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bd83bfa12f6251a7bb7637ad4ccd5d0";
  }

  static const char* value(const ::movo_msgs::PVA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bd83bfa12f6251aULL;
  static const uint64_t static_value2 = 0x7bb7637ad4ccd5d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::movo_msgs::PVA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movo_msgs/PVA";
  }

  static const char* value(const ::movo_msgs::PVA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movo_msgs::PVA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_rad\n\
float32 vel_rps\n\
float32 acc_rps2\n\
";
  }

  static const char* value(const ::movo_msgs::PVA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movo_msgs::PVA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_rad);
      stream.next(m.vel_rps);
      stream.next(m.acc_rps2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PVA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movo_msgs::PVA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movo_msgs::PVA_<ContainerAllocator>& v)
  {
    s << indent << "pos_rad: ";
    Printer<float>::stream(s, indent + "  ", v.pos_rad);
    s << indent << "vel_rps: ";
    Printer<float>::stream(s, indent + "  ", v.vel_rps);
    s << indent << "acc_rps2: ";
    Printer<float>::stream(s, indent + "  ", v.acc_rps2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVO_MSGS_MESSAGE_PVA_H
