# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from movo_msgs/PanTiltFdbk.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import movo_msgs.msg
import std_msgs.msg

class PanTiltFdbk(genpy.Message):
  _md5sum = "c294813db952ac45feb2086fe22222ab"
  _type = "movo_msgs/PanTiltFdbk"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
PanTiltActuatorFdbk pan
PanTiltActuatorFdbk tilt

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: movo_msgs/PanTiltActuatorFdbk
Header header
float32 current
float32 pos_rad
float32 vel_rps
float32 torque_nm
float32 pwm
float32 encoder_rad
geometry_msgs/Vector3 accel
float32 temperature_degC

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','pan','tilt']
  _slot_types = ['std_msgs/Header','movo_msgs/PanTiltActuatorFdbk','movo_msgs/PanTiltActuatorFdbk']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pan,tilt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PanTiltFdbk, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pan is None:
        self.pan = movo_msgs.msg.PanTiltActuatorFdbk()
      if self.tilt is None:
        self.tilt = movo_msgs.msg.PanTiltActuatorFdbk()
    else:
      self.header = std_msgs.msg.Header()
      self.pan = movo_msgs.msg.PanTiltActuatorFdbk()
      self.tilt = movo_msgs.msg.PanTiltActuatorFdbk()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.pan.header.seq, _x.pan.header.stamp.secs, _x.pan.header.stamp.nsecs))
      _x = self.pan.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6f3df3I.pack(_x.pan.current, _x.pan.pos_rad, _x.pan.vel_rps, _x.pan.torque_nm, _x.pan.pwm, _x.pan.encoder_rad, _x.pan.accel.x, _x.pan.accel.y, _x.pan.accel.z, _x.pan.temperature_degC, _x.tilt.header.seq, _x.tilt.header.stamp.secs, _x.tilt.header.stamp.nsecs))
      _x = self.tilt.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6f3df.pack(_x.tilt.current, _x.tilt.pos_rad, _x.tilt.vel_rps, _x.tilt.torque_nm, _x.tilt.pwm, _x.tilt.encoder_rad, _x.tilt.accel.x, _x.tilt.accel.y, _x.tilt.accel.z, _x.tilt.temperature_degC))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pan is None:
        self.pan = movo_msgs.msg.PanTiltActuatorFdbk()
      if self.tilt is None:
        self.tilt = movo_msgs.msg.PanTiltActuatorFdbk()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pan.header.seq, _x.pan.header.stamp.secs, _x.pan.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pan.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pan.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.pan.current, _x.pan.pos_rad, _x.pan.vel_rps, _x.pan.torque_nm, _x.pan.pwm, _x.pan.encoder_rad, _x.pan.accel.x, _x.pan.accel.y, _x.pan.accel.z, _x.pan.temperature_degC, _x.tilt.header.seq, _x.tilt.header.stamp.secs, _x.tilt.header.stamp.nsecs,) = _struct_6f3df3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tilt.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.tilt.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.tilt.current, _x.tilt.pos_rad, _x.tilt.vel_rps, _x.tilt.torque_nm, _x.tilt.pwm, _x.tilt.encoder_rad, _x.tilt.accel.x, _x.tilt.accel.y, _x.tilt.accel.z, _x.tilt.temperature_degC,) = _struct_6f3df.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.pan.header.seq, _x.pan.header.stamp.secs, _x.pan.header.stamp.nsecs))
      _x = self.pan.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6f3df3I.pack(_x.pan.current, _x.pan.pos_rad, _x.pan.vel_rps, _x.pan.torque_nm, _x.pan.pwm, _x.pan.encoder_rad, _x.pan.accel.x, _x.pan.accel.y, _x.pan.accel.z, _x.pan.temperature_degC, _x.tilt.header.seq, _x.tilt.header.stamp.secs, _x.tilt.header.stamp.nsecs))
      _x = self.tilt.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6f3df.pack(_x.tilt.current, _x.tilt.pos_rad, _x.tilt.vel_rps, _x.tilt.torque_nm, _x.tilt.pwm, _x.tilt.encoder_rad, _x.tilt.accel.x, _x.tilt.accel.y, _x.tilt.accel.z, _x.tilt.temperature_degC))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pan is None:
        self.pan = movo_msgs.msg.PanTiltActuatorFdbk()
      if self.tilt is None:
        self.tilt = movo_msgs.msg.PanTiltActuatorFdbk()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pan.header.seq, _x.pan.header.stamp.secs, _x.pan.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pan.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pan.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.pan.current, _x.pan.pos_rad, _x.pan.vel_rps, _x.pan.torque_nm, _x.pan.pwm, _x.pan.encoder_rad, _x.pan.accel.x, _x.pan.accel.y, _x.pan.accel.z, _x.pan.temperature_degC, _x.tilt.header.seq, _x.tilt.header.stamp.secs, _x.tilt.header.stamp.nsecs,) = _struct_6f3df3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tilt.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.tilt.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.tilt.current, _x.tilt.pos_rad, _x.tilt.vel_rps, _x.tilt.torque_nm, _x.tilt.pwm, _x.tilt.encoder_rad, _x.tilt.accel.x, _x.tilt.accel.y, _x.tilt.accel.z, _x.tilt.temperature_degC,) = _struct_6f3df.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f3df = struct.Struct("<6f3df")
_struct_3I = struct.Struct("<3I")
_struct_6f3df3I = struct.Struct("<6f3df3I")
