//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the movo_ros package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __movo_ros__MOVOCONFIG_H__
#define __movo_ros__MOVOCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace movo_ros
{
  class movoConfigStatics;
  
  class movoConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(movoConfig &config, const movoConfig &max, const movoConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const movoConfig &config1, const movoConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, movoConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const movoConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, movoConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const movoConfig &config) const = 0;
      virtual void getValue(const movoConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level, 
          std::string a_description, std::string a_edit_method, T movoConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (movoConfig::* field);

      virtual void clamp(movoConfig &config, const movoConfig &max, const movoConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const movoConfig &config1, const movoConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, movoConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const movoConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, movoConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const movoConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const movoConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, movoConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, movoConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<movoConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(movoConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class TELEOP_PAREMETERS
{
  public:
    TELEOP_PAREMETERS()
    {
      state = true;
      name = "Teleop_Paremeters";
    }

    void setParams(movoConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("teleop_x_vel_limit_mps"==(*_i)->name){teleop_x_vel_limit_mps = boost::any_cast<double>(val);}
        if("teleop_y_vel_limit_mps"==(*_i)->name){teleop_y_vel_limit_mps = boost::any_cast<double>(val);}
        if("teleop_accel_limit_mps2"==(*_i)->name){teleop_accel_limit_mps2 = boost::any_cast<double>(val);}
        if("teleop_yaw_rate_limit_rps"==(*_i)->name){teleop_yaw_rate_limit_rps = boost::any_cast<double>(val);}
        if("teleop_yaw_accel_limit_rps2"==(*_i)->name){teleop_yaw_accel_limit_rps2 = boost::any_cast<double>(val);}
        if("teleop_arm_vel_limit"==(*_i)->name){teleop_arm_vel_limit = boost::any_cast<double>(val);}
        if("teleop_pan_tilt_vel_limit"==(*_i)->name){teleop_pan_tilt_vel_limit = boost::any_cast<double>(val);}
        if("teleop_linear_actuator_vel_limit"==(*_i)->name){teleop_linear_actuator_vel_limit = boost::any_cast<double>(val);}
      }
    }

    double teleop_x_vel_limit_mps;
double teleop_y_vel_limit_mps;
double teleop_accel_limit_mps2;
double teleop_yaw_rate_limit_rps;
double teleop_yaw_accel_limit_rps2;
double teleop_arm_vel_limit;
double teleop_pan_tilt_vel_limit;
double teleop_linear_actuator_vel_limit;

    bool state;
    std::string name;

    
}teleop_paremeters;

class MACHINE_CONFIGURATION_PAREMETERS
{
  public:
    MACHINE_CONFIGURATION_PAREMETERS()
    {
      state = true;
      name = "Machine_Configuration_Paremeters";
    }

    void setParams(movoConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("x_vel_limit_mps"==(*_i)->name){x_vel_limit_mps = boost::any_cast<double>(val);}
        if("y_vel_limit_mps"==(*_i)->name){y_vel_limit_mps = boost::any_cast<double>(val);}
        if("accel_limit_mps2"==(*_i)->name){accel_limit_mps2 = boost::any_cast<double>(val);}
        if("decel_limit_mps2"==(*_i)->name){decel_limit_mps2 = boost::any_cast<double>(val);}
        if("dtz_decel_limit_mps2"==(*_i)->name){dtz_decel_limit_mps2 = boost::any_cast<double>(val);}
        if("yaw_rate_limit_rps"==(*_i)->name){yaw_rate_limit_rps = boost::any_cast<double>(val);}
        if("yaw_accel_limit_rps2"==(*_i)->name){yaw_accel_limit_rps2 = boost::any_cast<double>(val);}
        if("wheel_diameter_m"==(*_i)->name){wheel_diameter_m = boost::any_cast<double>(val);}
        if("wheel_base_length_m"==(*_i)->name){wheel_base_length_m = boost::any_cast<double>(val);}
        if("wheel_track_width_m"==(*_i)->name){wheel_track_width_m = boost::any_cast<double>(val);}
        if("gear_ratio"==(*_i)->name){gear_ratio = boost::any_cast<double>(val);}
        if("motion_while_charging"==(*_i)->name){motion_while_charging = boost::any_cast<bool>(val);}
        if("motion_ctl_input_filter"==(*_i)->name){motion_ctl_input_filter = boost::any_cast<int>(val);}
        if("linear_actuator_vel_limit_mps"==(*_i)->name){linear_actuator_vel_limit_mps = boost::any_cast<double>(val);}
      }
    }

    double x_vel_limit_mps;
double y_vel_limit_mps;
double accel_limit_mps2;
double decel_limit_mps2;
double dtz_decel_limit_mps2;
double yaw_rate_limit_rps;
double yaw_accel_limit_rps2;
double wheel_diameter_m;
double wheel_base_length_m;
double wheel_track_width_m;
double gear_ratio;
bool motion_while_charging;
int motion_ctl_input_filter;
double linear_actuator_vel_limit_mps;

    bool state;
    std::string name;

    
}machine_configuration_paremeters;

class CORRECTION_FACTORS
{
  public:
    CORRECTION_FACTORS()
    {
      state = true;
      name = "Correction_Factors";
    }

    void setParams(movoConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("strafe_correction_factor"==(*_i)->name){strafe_correction_factor = boost::any_cast<double>(val);}
        if("yaw_correction_factor"==(*_i)->name){yaw_correction_factor = boost::any_cast<double>(val);}
      }
    }

    double strafe_correction_factor;
double yaw_correction_factor;

    bool state;
    std::string name;

    
}correction_factors;

}groups;



//#line 9 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_x_vel_limit_mps;
//#line 10 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_y_vel_limit_mps;
//#line 11 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_accel_limit_mps2;
//#line 12 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_yaw_rate_limit_rps;
//#line 13 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_yaw_accel_limit_rps2;
//#line 15 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_arm_vel_limit;
//#line 17 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_pan_tilt_vel_limit;
//#line 19 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double teleop_linear_actuator_vel_limit;
//#line 23 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double x_vel_limit_mps;
//#line 24 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double y_vel_limit_mps;
//#line 25 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double accel_limit_mps2;
//#line 26 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double decel_limit_mps2;
//#line 27 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double dtz_decel_limit_mps2;
//#line 28 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double yaw_rate_limit_rps;
//#line 29 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double yaw_accel_limit_rps2;
//#line 30 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double wheel_diameter_m;
//#line 31 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double wheel_base_length_m;
//#line 32 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double wheel_track_width_m;
//#line 33 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double gear_ratio;
//#line 35 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      bool motion_while_charging;
//#line 45 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      int motion_ctl_input_filter;
//#line 47 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double linear_actuator_vel_limit_mps;
//#line 50 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double strafe_correction_factor;
//#line 51 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      double yaw_correction_factor;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("movoConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const movoConfig &__max__ = __getMax__();
      const movoConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const movoConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const movoConfig &__getDefault__();
    static const movoConfig &__getMax__();
    static const movoConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const movoConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void movoConfig::ParamDescription<std::string>::clamp(movoConfig &config, const movoConfig &max, const movoConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class movoConfigStatics
  {
    friend class movoConfig;
    
    movoConfigStatics()
    {
movoConfig::GroupDescription<movoConfig::DEFAULT, movoConfig> Default("Default", "", 0, 0, true, &movoConfig::groups);
movoConfig::GroupDescription<movoConfig::DEFAULT::TELEOP_PAREMETERS, movoConfig::DEFAULT> Teleop_Paremeters("Teleop_Paremeters", "", 0, 1, true, &movoConfig::DEFAULT::teleop_paremeters);
//#line 9 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_x_vel_limit_mps = 0.0;
//#line 9 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_x_vel_limit_mps = 2.0;
//#line 9 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_x_vel_limit_mps = 0.5;
//#line 9 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_x_vel_limit_mps", "double", 2, "Maximum velocity in m/s for teleop", "", &movoConfig::teleop_x_vel_limit_mps)));
//#line 9 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_x_vel_limit_mps", "double", 2, "Maximum velocity in m/s for teleop", "", &movoConfig::teleop_x_vel_limit_mps)));
//#line 10 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_y_vel_limit_mps = 0.0;
//#line 10 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_y_vel_limit_mps = 1.0;
//#line 10 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_y_vel_limit_mps = 0.5;
//#line 10 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_y_vel_limit_mps", "double", 2, "Maximum velocity in m/s for teleop", "", &movoConfig::teleop_y_vel_limit_mps)));
//#line 10 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_y_vel_limit_mps", "double", 2, "Maximum velocity in m/s for teleop", "", &movoConfig::teleop_y_vel_limit_mps)));
//#line 11 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_accel_limit_mps2 = 0.05;
//#line 11 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_accel_limit_mps2 = 2.5;
//#line 11 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_accel_limit_mps2 = 0.5;
//#line 11 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_accel_limit_mps2", "double", 2, "Maximum velocity in m/s for teleop", "", &movoConfig::teleop_accel_limit_mps2)));
//#line 11 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_accel_limit_mps2", "double", 2, "Maximum velocity in m/s for teleop", "", &movoConfig::teleop_accel_limit_mps2)));
//#line 12 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_yaw_rate_limit_rps = 0.0;
//#line 12 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_yaw_rate_limit_rps = 3.2;
//#line 12 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_yaw_rate_limit_rps = 1.0;
//#line 12 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_yaw_rate_limit_rps", "double", 2, "Maximum yaw_rate in rad/s for teleop", "", &movoConfig::teleop_yaw_rate_limit_rps)));
//#line 12 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_yaw_rate_limit_rps", "double", 2, "Maximum yaw_rate in rad/s for teleop", "", &movoConfig::teleop_yaw_rate_limit_rps)));
//#line 13 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_yaw_accel_limit_rps2 = 0.063;
//#line 13 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_yaw_accel_limit_rps2 = 6.28;
//#line 13 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_yaw_accel_limit_rps2 = 1.0;
//#line 13 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_yaw_accel_limit_rps2", "double", 2, "Maximum yaw acceleration in rad/s^2 for teleop", "", &movoConfig::teleop_yaw_accel_limit_rps2)));
//#line 13 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_yaw_accel_limit_rps2", "double", 2, "Maximum yaw acceleration in rad/s^2 for teleop", "", &movoConfig::teleop_yaw_accel_limit_rps2)));
//#line 15 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_arm_vel_limit = 0.0;
//#line 15 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_arm_vel_limit = 0.2;
//#line 15 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_arm_vel_limit = 0.1;
//#line 15 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_arm_vel_limit", "double", 2, "Maximum arm cartesian velocity in cm/s", "", &movoConfig::teleop_arm_vel_limit)));
//#line 15 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_arm_vel_limit", "double", 2, "Maximum arm cartesian velocity in cm/s", "", &movoConfig::teleop_arm_vel_limit)));
//#line 17 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_pan_tilt_vel_limit = 0.0;
//#line 17 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_pan_tilt_vel_limit = 0.872;
//#line 17 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_pan_tilt_vel_limit = 0.524;
//#line 17 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_pan_tilt_vel_limit", "double", 2, "Maximum pan_tilt velocity in rad/s for teleop", "", &movoConfig::teleop_pan_tilt_vel_limit)));
//#line 17 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_pan_tilt_vel_limit", "double", 2, "Maximum pan_tilt velocity in rad/s for teleop", "", &movoConfig::teleop_pan_tilt_vel_limit)));
//#line 19 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.teleop_linear_actuator_vel_limit = 0.0;
//#line 19 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.teleop_linear_actuator_vel_limit = 0.1;
//#line 19 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.teleop_linear_actuator_vel_limit = 0.05;
//#line 19 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Teleop_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_linear_actuator_vel_limit", "double", 2, "Maximum linear actuator velocity limit in m/s for teleop", "", &movoConfig::teleop_linear_actuator_vel_limit)));
//#line 19 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("teleop_linear_actuator_vel_limit", "double", 2, "Maximum linear actuator velocity limit in m/s for teleop", "", &movoConfig::teleop_linear_actuator_vel_limit)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Teleop_Paremeters.convertParams();
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT::TELEOP_PAREMETERS, movoConfig::DEFAULT>(Teleop_Paremeters)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT::TELEOP_PAREMETERS, movoConfig::DEFAULT>(Teleop_Paremeters)));
movoConfig::GroupDescription<movoConfig::DEFAULT::MACHINE_CONFIGURATION_PAREMETERS, movoConfig::DEFAULT> Machine_Configuration_Paremeters("Machine_Configuration_Paremeters", "", 0, 2, true, &movoConfig::DEFAULT::machine_configuration_paremeters);
//#line 23 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.x_vel_limit_mps = 0.0;
//#line 23 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.x_vel_limit_mps = 2.0;
//#line 23 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.x_vel_limit_mps = 1.0;
//#line 23 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("x_vel_limit_mps", "double", 4, "Maximum forward velocity in m/s for Movo", "", &movoConfig::x_vel_limit_mps)));
//#line 23 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("x_vel_limit_mps", "double", 4, "Maximum forward velocity in m/s for Movo", "", &movoConfig::x_vel_limit_mps)));
//#line 24 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.y_vel_limit_mps = 0.0;
//#line 24 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.y_vel_limit_mps = 1.0;
//#line 24 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.y_vel_limit_mps = 0.5;
//#line 24 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("y_vel_limit_mps", "double", 4, "Maximum strafe velocity in m/s for Movo", "", &movoConfig::y_vel_limit_mps)));
//#line 24 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("y_vel_limit_mps", "double", 4, "Maximum strafe velocity in m/s for Movo", "", &movoConfig::y_vel_limit_mps)));
//#line 25 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.accel_limit_mps2 = 0.05;
//#line 25 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.accel_limit_mps2 = 2.5;
//#line 25 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.accel_limit_mps2 = 0.5;
//#line 25 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("accel_limit_mps2", "double", 4, "Maximum acceleration in m/s^2 for Movo", "", &movoConfig::accel_limit_mps2)));
//#line 25 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("accel_limit_mps2", "double", 4, "Maximum acceleration in m/s^2 for Movo", "", &movoConfig::accel_limit_mps2)));
//#line 26 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.decel_limit_mps2 = 0.05;
//#line 26 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.decel_limit_mps2 = 2.5;
//#line 26 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.decel_limit_mps2 = 0.5;
//#line 26 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("decel_limit_mps2", "double", 4, "Maximum deceleration in m/s^2 for Movo", "", &movoConfig::decel_limit_mps2)));
//#line 26 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("decel_limit_mps2", "double", 4, "Maximum deceleration in m/s^2 for Movo", "", &movoConfig::decel_limit_mps2)));
//#line 27 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.dtz_decel_limit_mps2 = 0.981;
//#line 27 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.dtz_decel_limit_mps2 = 2.5;
//#line 27 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.dtz_decel_limit_mps2 = 1.0;
//#line 27 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("dtz_decel_limit_mps2", "double", 4, "Maximum emergency DTZ deceleration in m/s^2 for Movo", "", &movoConfig::dtz_decel_limit_mps2)));
//#line 27 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("dtz_decel_limit_mps2", "double", 4, "Maximum emergency DTZ deceleration in m/s^2 for Movo", "", &movoConfig::dtz_decel_limit_mps2)));
//#line 28 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.yaw_rate_limit_rps = 0.0;
//#line 28 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.yaw_rate_limit_rps = 3.2;
//#line 28 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.yaw_rate_limit_rps = 1.0;
//#line 28 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("yaw_rate_limit_rps", "double", 4, "Maximum yaw rate in rad/s for Movo", "", &movoConfig::yaw_rate_limit_rps)));
//#line 28 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("yaw_rate_limit_rps", "double", 4, "Maximum yaw rate in rad/s for Movo", "", &movoConfig::yaw_rate_limit_rps)));
//#line 29 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.yaw_accel_limit_rps2 = 0.063;
//#line 29 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.yaw_accel_limit_rps2 = 6.28;
//#line 29 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.yaw_accel_limit_rps2 = 1.0;
//#line 29 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("yaw_accel_limit_rps2", "double", 4, "Maximum yaw acceleration in rad/s^2 for Movo", "", &movoConfig::yaw_accel_limit_rps2)));
//#line 29 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("yaw_accel_limit_rps2", "double", 4, "Maximum yaw acceleration in rad/s^2 for Movo", "", &movoConfig::yaw_accel_limit_rps2)));
//#line 30 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.wheel_diameter_m = 0.1324;
//#line 30 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.wheel_diameter_m = 0.1724;
//#line 30 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.wheel_diameter_m = 0.1524;
//#line 30 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("wheel_diameter_m", "double", 4, "wheel diameter in m for Movo", "", &movoConfig::wheel_diameter_m)));
//#line 30 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("wheel_diameter_m", "double", 4, "wheel diameter in m for Movo", "", &movoConfig::wheel_diameter_m)));
//#line 31 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.wheel_base_length_m = 0.48173;
//#line 31 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.wheel_base_length_m = 0.52173;
//#line 31 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.wheel_base_length_m = 0.50173;
//#line 31 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("wheel_base_length_m", "double", 4, "Distance between front and rear contact patch in m for Movo", "", &movoConfig::wheel_base_length_m)));
//#line 31 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("wheel_base_length_m", "double", 4, "Distance between front and rear contact patch in m for Movo", "", &movoConfig::wheel_base_length_m)));
//#line 32 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.wheel_track_width_m = 0.40835;
//#line 32 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.wheel_track_width_m = 0.44835;
//#line 32 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.wheel_track_width_m = 0.42835;
//#line 32 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("wheel_track_width_m", "double", 4, "Distance between left and right contact patch in m for Movo", "", &movoConfig::wheel_track_width_m)));
//#line 32 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("wheel_track_width_m", "double", 4, "Distance between left and right contact patch in m for Movo", "", &movoConfig::wheel_track_width_m)));
//#line 33 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.gear_ratio = 1.0;
//#line 33 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.gear_ratio = 50.0;
//#line 33 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.gear_ratio = 5.0;
//#line 33 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("gear_ratio", "double", 4, "Input to ouput gear ratio for Movo", "", &movoConfig::gear_ratio)));
//#line 33 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("gear_ratio", "double", 4, "Input to ouput gear ratio for Movo", "", &movoConfig::gear_ratio)));
//#line 35 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.motion_while_charging = 0;
//#line 35 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.motion_while_charging = 1;
//#line 35 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.motion_while_charging = 0;
//#line 35 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<bool>("motion_while_charging", "bool", 4, "Allow motion with charger connected", "", &movoConfig::motion_while_charging)));
//#line 35 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<bool>("motion_while_charging", "bool", 4, "Allow motion with charger connected", "", &movoConfig::motion_while_charging)));
//#line 45 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.motion_ctl_input_filter = -2147483648;
//#line 45 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.motion_ctl_input_filter = 2147483647;
//#line 45 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.motion_ctl_input_filter = 0;
//#line 45 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<int>("motion_ctl_input_filter", "int", 4, "Motion Controller Input Filter Cutoff", "{'enum_description': 'Motion controller input filter cutoff frequency', 'enum': [{'srcline': 39, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'filter_10Hz_Cutoff'}, {'srcline': 40, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'filter_4Hz_Cutoff'}, {'srcline': 41, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'filter_1Hz_Cutoff'}, {'srcline': 42, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'filter_0p5Hz_Cutoff'}, {'srcline': 43, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 8, 'ctype': 'int', 'type': 'int', 'name': 'filter_0p2Hz_Cutoff'}]}", &movoConfig::motion_ctl_input_filter)));
//#line 45 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<int>("motion_ctl_input_filter", "int", 4, "Motion Controller Input Filter Cutoff", "{'enum_description': 'Motion controller input filter cutoff frequency', 'enum': [{'srcline': 39, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'filter_10Hz_Cutoff'}, {'srcline': 40, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'filter_4Hz_Cutoff'}, {'srcline': 41, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'filter_1Hz_Cutoff'}, {'srcline': 42, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'filter_0p5Hz_Cutoff'}, {'srcline': 43, 'description': '', 'srcfile': '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg', 'cconsttype': 'const int', 'value': 8, 'ctype': 'int', 'type': 'int', 'name': 'filter_0p2Hz_Cutoff'}]}", &movoConfig::motion_ctl_input_filter)));
//#line 47 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.linear_actuator_vel_limit_mps = 0.0;
//#line 47 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.linear_actuator_vel_limit_mps = 0.2;
//#line 47 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.linear_actuator_vel_limit_mps = 0.1;
//#line 47 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Machine_Configuration_Paremeters.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("linear_actuator_vel_limit_mps", "double", 8, "Maximum velocity for the linear actuator", "", &movoConfig::linear_actuator_vel_limit_mps)));
//#line 47 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("linear_actuator_vel_limit_mps", "double", 8, "Maximum velocity for the linear actuator", "", &movoConfig::linear_actuator_vel_limit_mps)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Machine_Configuration_Paremeters.convertParams();
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT::MACHINE_CONFIGURATION_PAREMETERS, movoConfig::DEFAULT>(Machine_Configuration_Paremeters)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT::MACHINE_CONFIGURATION_PAREMETERS, movoConfig::DEFAULT>(Machine_Configuration_Paremeters)));
movoConfig::GroupDescription<movoConfig::DEFAULT::CORRECTION_FACTORS, movoConfig::DEFAULT> Correction_Factors("Correction_Factors", "", 0, 3, true, &movoConfig::DEFAULT::correction_factors);
//#line 50 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.strafe_correction_factor = -0.5;
//#line 50 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.strafe_correction_factor = 0.5;
//#line 50 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.strafe_correction_factor = 0.0;
//#line 50 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Correction_Factors.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("strafe_correction_factor", "double", 16, "factor applied to y odometry components to correct for straying angle variation surface to surface", "", &movoConfig::strafe_correction_factor)));
//#line 50 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("strafe_correction_factor", "double", 16, "factor applied to y odometry components to correct for straying angle variation surface to surface", "", &movoConfig::strafe_correction_factor)));
//#line 51 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __min__.yaw_correction_factor = -0.5;
//#line 51 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __max__.yaw_correction_factor = 0.5;
//#line 51 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __default__.yaw_correction_factor = 0.0;
//#line 51 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      Correction_Factors.abstract_parameters.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("yaw_correction_factor", "double", 32, "factor applied to yaw odometry components to correct for straying angle variation surface to surface", "", &movoConfig::yaw_correction_factor)));
//#line 51 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      __param_descriptions__.push_back(movoConfig::AbstractParamDescriptionConstPtr(new movoConfig::ParamDescription<double>("yaw_correction_factor", "double", 32, "factor applied to yaw odometry components to correct for straying angle variation surface to surface", "", &movoConfig::yaw_correction_factor)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Correction_Factors.convertParams();
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT::CORRECTION_FACTORS, movoConfig::DEFAULT>(Correction_Factors)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT::CORRECTION_FACTORS, movoConfig::DEFAULT>(Correction_Factors)));
//#line 246 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(movoConfig::AbstractGroupDescriptionConstPtr(new movoConfig::GroupDescription<movoConfig::DEFAULT, movoConfig>(Default)));
//#line 356 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<movoConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<movoConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<movoConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    movoConfig __max__;
    movoConfig __min__;
    movoConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const movoConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static movoConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &movoConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const movoConfig &movoConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const movoConfig &movoConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const movoConfig &movoConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<movoConfig::AbstractParamDescriptionConstPtr> &movoConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<movoConfig::AbstractGroupDescriptionConstPtr> &movoConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const movoConfigStatics *movoConfig::__get_statics__()
  {
    const static movoConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = movoConfigStatics::get_instance();
    
    return statics;
  }

//#line 39 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      const int movo_filter_10Hz_Cutoff = 0;
//#line 40 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      const int movo_filter_4Hz_Cutoff = 1;
//#line 41 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      const int movo_filter_1Hz_Cutoff = 2;
//#line 42 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      const int movo_filter_0p5Hz_Cutoff = 4;
//#line 43 "/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_ros/cfg/movo.cfg"
      const int movo_filter_0p2Hz_Cutoff = 8;
}

#endif // __MOVORECONFIGURATOR_H__
