// Generated by gencpp from file grasp_msgs/FindGraspableObjectsActionGoal.msg
// DO NOT EDIT!


#ifndef GRASP_MSGS_MESSAGE_FINDGRASPABLEOBJECTSACTIONGOAL_H
#define GRASP_MSGS_MESSAGE_FINDGRASPABLEOBJECTSACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <grasp_msgs/FindGraspableObjectsGoal.h>

namespace grasp_msgs
{
template <class ContainerAllocator>
struct FindGraspableObjectsActionGoal_
{
  typedef FindGraspableObjectsActionGoal_<ContainerAllocator> Type;

  FindGraspableObjectsActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FindGraspableObjectsActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FindGraspableObjectsActionGoal_

typedef ::grasp_msgs::FindGraspableObjectsActionGoal_<std::allocator<void> > FindGraspableObjectsActionGoal;

typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsActionGoal > FindGraspableObjectsActionGoalPtr;
typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsActionGoal const> FindGraspableObjectsActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'grasp_msgs': ['/home/andrewandjasmine/movo_ws/devel/share/grasp_msgs/msg', '/home/andrewandjasmine/movo_ws/src/movo_kinova/movo_common/movo_third_party/grasp_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83b486077a5c6b36d8d1595e0f372e37";
  }

  static const char* value(const ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83b486077a5c6b36ULL;
  static const uint64_t static_value2 = 0xd8d1595e0f372e37ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_msgs/FindGraspableObjectsActionGoal";
  }

  static const char* value(const ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FindGraspableObjectsGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: grasp_msgs/FindGraspableObjectsGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
###########################################################\n\
# This action is called for integrated object detection and\n\
#  grasp planning, such as in base_grasping_perception\n\
\n\
# Set to false to disable grasp planning, returning only the objects found\n\
bool plan_grasps\n\
int32 gripper\n\
";
  }

  static const char* value(const ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindGraspableObjectsActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_msgs::FindGraspableObjectsActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_MSGS_MESSAGE_FINDGRASPABLEOBJECTSACTIONGOAL_H
