// Generated by gencpp from file grasp_msgs/FindGraspableObjectsGoal.msg
// DO NOT EDIT!


#ifndef GRASP_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H
#define GRASP_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_msgs
{
template <class ContainerAllocator>
struct FindGraspableObjectsGoal_
{
  typedef FindGraspableObjectsGoal_<ContainerAllocator> Type;

  FindGraspableObjectsGoal_()
    : plan_grasps(false)
    , gripper(0)  {
    }
  FindGraspableObjectsGoal_(const ContainerAllocator& _alloc)
    : plan_grasps(false)
    , gripper(0)  {
  (void)_alloc;
    }



   typedef uint8_t _plan_grasps_type;
  _plan_grasps_type plan_grasps;

   typedef int32_t _gripper_type;
  _gripper_type gripper;




  typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FindGraspableObjectsGoal_

typedef ::grasp_msgs::FindGraspableObjectsGoal_<std::allocator<void> > FindGraspableObjectsGoal;

typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsGoal > FindGraspableObjectsGoalPtr;
typedef boost::shared_ptr< ::grasp_msgs::FindGraspableObjectsGoal const> FindGraspableObjectsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'grasp_msgs': ['/home/andrewandjasmine/movo_ws/devel/share/grasp_msgs/msg', '/home/andrewandjasmine/movo_ws/src/movo_common/movo_third_party/grasp_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fef75b0b9e44a21afd1ab66a4bc34d9";
  }

  static const char* value(const ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fef75b0b9e44a21ULL;
  static const uint64_t static_value2 = 0xafd1ab66a4bc34d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_msgs/FindGraspableObjectsGoal";
  }

  static const char* value(const ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
###########################################################\n\
# This action is called for integrated object detection and\n\
#  grasp planning, such as in base_grasping_perception\n\
\n\
# Set to false to disable grasp planning, returning only the objects found\n\
bool plan_grasps\n\
int32 gripper\n\
";
  }

  static const char* value(const ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_grasps);
      stream.next(m.gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindGraspableObjectsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_msgs::FindGraspableObjectsGoal_<ContainerAllocator>& v)
  {
    s << indent << "plan_grasps: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_grasps);
    s << indent << "gripper: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H
